### ISSUE TITLE
Python 3 migration

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#331]
Python 2 has reached EOL and we need to migrate to python 3 ASAP.

Requirements to be able to do this robustly are:

- [x] Improved automated [testing of style and syntactic issues](https://github.com/ParaToolsInc/taucmdr/issues/332)
- [ ] Use mypy to [enforce type checking on Python 2 code](https://github.com/ParaToolsInc/taucmdr/issues/333)
- [x] [Migrate testing from Travis-CI to GH actions](https://github.com/ParaToolsInc/taucmdr/issues/334)
- [x] Add [additional tests](https://github.com/ParaToolsInc/taucmdr/issues/336), including [nightly and integration](https://github.com/ParaToolsInc/taucmdr/issues/335) tests

The biggest challenge is surrounding Python 3's handling of strings using two different underlying types: One uses encoding as byte strings and the other is UTF-8 encoded. The arguments on stdin and results on stdout and stderr from spawned processes are especially challenging to detect and convert.

Type checking will make debugging easier in general, and will enable catching cases were there is an unexpected type mismatch in arguments.

**Comment by nchaimov** [comment]
This was fixed by #404
